### ISSUE TITLE
Installing k-gnn on windows

### ISSUE THREAD

**Issue by Ana-hita** [chrsmrrs/k-gnn#14]
Hi,

I am trying to install this package on my windows, I already have `torch 1.5.1+cu101`, and `torch_geometric` version 1.6.1, yet I am unable to install k-gnn on my system, and I don't know how to resolve it. 

Here is the error while installing k-gnn:

> python setup.py install
running install
running bdist_egg
running egg_info
writing k_gnn.egg-info\PKG-INFO
writing dependency_links to k_gnn.egg-info\dependency_links.txt
writing top-level names to k_gnn.egg-info\top_level.txt
reading manifest file 'k_gnn.egg-info\SOURCES.txt'
writing manifest file 'k_gnn.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
C:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'graph_cpu' extension
Emitting ninja build file C:\Users\user\k-gnn-master\k-gnn-master\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include\TH -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include\THC -IC:\Users\user\anaconda3\envs\py36\include -IC:\Users\user\anaconda3\envs\py36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\user\k-gnn-master\k-gnn-master\cpu\graph.cpp /FoC:\Users\user\k-gnn-master\k-gnn-master\build\temp.win-amd64-3.6\Release\cpu/graph.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=graph_cpu -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/user/k-gnn-master/k-gnn-master/build/temp.win-amd64-3.6/Release/cpu/graph.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include\TH -IC:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\include\THC -IC:\Users\user\anaconda3\envs\py36\include -IC:\Users\user\anaconda3\envs\py36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\user\k-gnn-master\k-gnn-master\cpu\graph.cpp /FoC:\Users\user\k-gnn-master\k-gnn-master\build\temp.win-amd64-3.6\Release\cpu/graph.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=graph_cpu -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "C:\Users\user\anaconda3\envs\py36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    packages=find_packages(),
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\bdist_egg.py", line 175, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\user\anaconda3\envs\py36\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\user\anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

Thank you in advance for your help.

**Comment by rusty1s** [comment]
[This](https://discuss.pytorch.org/t/error-with-cpp-extentions/67559) might be related.

**Comment by Ana-hita** [comment]
Thank you very much for the link. I could resolve the problem.

For those who might face the same issue, I have followed [this](https://discuss.pytorch.org/t/error-with-cpp-extentions/67559/4) answer, running "x64 Native Tools Command Prompt for VS 2019" and installing k-gnn in that environment.
