### ISSUE TITLE
urllib.error.URLError on 1-2-3-proteins.py

### ISSUE THREAD

**Issue by spark157** [chrsmrrs/k-gnn#3]
Hello,

I'm just trying to run the example program: python 1-2-3-proteins.py and get the following:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'ls11-www.cs.uni-dortmund.de'. (_ssl.c:1056)>

I'm on MacOS 10.14.4, python 3.7, anaconda.

Thanks if you can help.

Scott

> python 1-2-3-proteins.py
Downloading https://ls11-www.cs.uni-dortmund.de/people/morris/graphkerneldatasets/PROTEINS.zip
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/anaconda3/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/anaconda3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/anaconda3/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/anaconda3/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'ls11-www.cs.uni-dortmund.de'. (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1-2-3-proteins.py", line 39, in <module>
    pre_filter=MyFilter())
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 48, in __init__
    pre_filter)
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 56, in __init__
    pre_filter)
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 82, in __init__
    self._download()
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 108, in _download
    self.download()
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 81, in download
    path = download_url('{}/{}.zip'.format(self.url, self.name), self.root)
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/data/download.py", line 23, in download_url
    data = urllib.request.urlopen(url)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'ls11-www.cs.uni-dortmund.de'. (_ssl.c:1056)>

**Comment by rusty1s** [comment]
This is a PyG error and is fixed in current master. Editing the source file of `torch_geometric.datasets.TUDataset` according to [this](https://github.com/rusty1s/pytorch_geometric/commit/90a06d02b79414fc48a3367c79cfb28f919d5769#commitcomment-33852244) should get you going.

**Comment by spark157** [comment]
Thanks! That did it.
